### ISSUE TITLE
你解决这个了吗

### ISSUE THREAD

**Issue by IConquer96** [KhyatiMehta3/AutRcCar#1]
Hi, I'm getting this error:

On computer:

Start collecting images...
Traceback (most recent call last):
File "collect_training_data.py", line 174, in 
CollectTrainingData()
File "collect_training_data.py", line 36, in init
self.collect_image()
File "collect_training_data.py", line 55, in collect_image
stream_bytes += self.connection.read(1024)
TypeError: must be str, not bytes

On RaspberryPi 3:

Traceback (most srecent call last):
File "stream_client.py", line50, in 
connection.close()
File "/usr/lib/python2.7/socket.py", line 283, in close
self.flush()
File "/usr/lib/python2.7/socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

Can you help me solve it?

**Comment by kkmehta03** [comment]
convert your code in collect_training_data.py to this:
try:
            stream_bytes = bytes()
            frame = 1
            while self.send_inst:
                stream_bytes += self.connection.read(1024)
                first = stream_bytes.find(b'\xff\xd8')
                last = stream_bytes.find(b'\xff\xd9')

**Comment by IConquer96** [comment]
i used the struct to unpack the bytes,change the code to this:
connection = self.cam_socket.accept()[0].makefile('rb')
        try:
            while True:
                image_len = struct.unpack('<L', connection.read(struct.calcsize('<L')))[0]

and it workd!!!thank you anyway!
